micronaut:
  security:
    filter:
      enabled: false

application:
  db:
    flyway:
      host: ${DB_RUNTIME_HOST:`10.248.36.241`}
      port: ${DB_RUNTIME_PORT:`5432`}
      db-name: ${DB_RUNTIME_DB_NAME:`postgres`}
      username: ${DB_RUNTIME_USERNAME:`postgres`}
      password: ${DB_RUNTIME_PASSWORD:`Tempa55123!!`}
      sslmode: ${DB_RUNTIME_SSL:`prefer`} #verify-ca

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: ${DB_RUNTIME_CLEAN_SCHEMA:`true`}   # "true" for test and development purpose only
      url: jdbc:postgresql://${application.db.flyway.host}:${application.db.flyway.port}/${application.db.flyway.db-name}?sslmode=${application.db.flyway.sslmode}
      username: ${application.db.flyway.username}
      password: ${application.db.flyway.password}
      schemas: dbmigrator
      locations:
        - s3://are-aws-lambda-deployment-bucket
      init-sql: ${DB_RUNTIME_INIT_SQL:} # "drop schema if exists ps cascade" for test and development purpose only
      out-of-order: true